name: Backup Songs

on:
  schedule:
    - cron: "0 0 * * 0"    # Every week (Sunday at 00:00 UTC)
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backup script
        id: run_backup
        env:
          CHORDS_AND_TABS_COOKIES: ${{ secrets.CHORDS_AND_TABS_COOKIES }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python GOOD_automatic_backup.py

      - name: Check for debug screenshot
        id: check_debug
        run: |
          if [ -f debug_screenshot.png ]; then
              echo "found=true" >> $GITHUB_OUTPUT;
          else
              echo "found=false" >> $GITHUB_OUTPUT;
          fi

      - name: Upload debug screenshot
        if: steps.check_debug.outputs.found == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: debug_screenshot
          path: debug_screenshot.png
